name: Hourly tweet
on:
  schedule:
    - cron: "0 3,6,9,12,15,18,21 * * *"
jobs:
  tweet:
    runs-on: ubuntu-latest
    env:
      ARSAT: ${{ secrets.ARSAT }}
      AT: ${{ secrets.ACCESS_TOKEN }}
      ATS: ${{ secrets.ACCESS_TOKEN_SECRET }}
      AK: ${{ secrets.API_KEY }}
      AKS: ${{ secrets.API_KEY_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Tweet
        run: curl --request GET --url "$ARSAT/hour?at=$AT&ats=$ATS&ak=$AK&aks=$AKS"
