name: tweet
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      ARSAT: ${{ secrets.ARSAT }}
      AT: ${{ secrets.ACCESS_TOKEN }}
      ATS: ${{ secrets.ACCESS_TOKEN_SECRET }}
      AK: ${{ secrets.API_KEY }}
      AKS: ${{ secrets.API_KEY_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Test tweet
        run: curl --request GET --url "$ARSAT/tweet?at=$AT&ats=$ATS&ak=$AK&aks=$AKS"
